### ISSUE TITLE
Request : Icon Location 

### ISSUE THREAD

**Issue by jbblily** [jsinme/fvtt-bcdice#24]
![캡처](https://user-images.githubusercontent.com/18694887/112261020-5862cc00-8cae-11eb-9210-87cfb85120e0.PNG)

Hello, I'm using Minimal UI Module for my convenience.
I think it would be more convenient if the BC Dice Icon moves under the sidebar icon group of character token, so that it does not breaks other UI modules.
It is a tiny, small request but please consider this. 
Thank you for your nice work.

**Comment by BrotherSharper** [comment]
possibly related to #23

**Comment by jsinme** [comment]
Hmmm, this is interesting. I'll have to play around with it to see how UI modules apply styles. But yes, I'll definitely try to resolve this soon.

**Comment by jsinme** [comment]
@jbblily I've modified the way the control is loaded in so it shouldn't stick out so much anymore. It's not under the character token subgroup because I don't think that necessarily makes sense grouping wise. I'm looking at ways to make its location configurable but that will be something I work on later.
